### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by Tigster** [Patcher56/PatchProtect#100]
Is it possible if you could add a button under cleanprops which will delete props not owned by anyone?
Cheers

**Comment by Domii894** [comment]
Props, which are not owned by anyone will be owned by the first person, who tries to interact with it.
But I could add something, which would fullfill your wish, but not yet. I'm quite busy at the moment.

**Comment by Tigster** [comment]
Okay thanks

**Comment by Domii894** [comment]
Ok, so as you can see, I added your requested feature :)
Please have in mind that this feature is not included in the workshop version yet. It will be available with the next update. Just check the update history of the workshop version.
