### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Tigster** [Patcher56/PatchProtect#102]
[ERROR] addons/patchprotect-master/lua/autorun/cppi.lua:49: Tried to use a NULL entity!
  1. UniqueID - [C]:-1
   2. CPPIGetOwner - addons/patchprotect-master/lua/autorun/cppi.lua:49
    3. v - addons/patchprotect-master/lua/patchprotect/server/propprotection.lua:312
     4. unknown - lua/includes/modules/hook.lua:84

**Comment by Domii894** [comment]
So I changed the code a bit to hopefully fix this. This fix is not on workshop, so maybe you could test the newest version from github?
Normally it should work with this fix, but I'm not 100% sure.
So with this link (https://github.com/Patcher56/PatchProtect/archive/master.zip) you would be able to download the github version

**Comment by Domii894** [comment]
I will close this. If you still experience this issue with the newest github version, then feel free to reopen that issue and I will have another look at it.
Thanks.

**Comment by Tigster** [comment]
Ok mate
