### ISSUE TITLE
Random Error

### ISSUE THREAD

**Issue by ickycoolboy** [Patcher56/PatchProtect#103]
Error in hook HUDPaint: addons/patchprotect/lua/patchprotect/client/hud.lua:37: Tried to use a NULL entity!
stack traceback:
[C]: in function 'Nick'
addons/patchprotect/lua/patchprotect/client/hud.lua:37: in function 'fn'
addons/ulib/lua/ulib/shared/hook.lua:105: in function <addons/ulib/lua/ulib/shared/hook.lua:88>
[C]: in function '‭‬‌⁬﻿‎⁯⁮⁭'

[ERROR] 
  1. unknown - [C]:-1

I could not find a pattern to this error, It seems to happen randomly or possibly a little while after a map change.

**Comment by Domii894** [comment]
Thank you for your error report.
The github-version should be fixed. I will have a look to get the newest version on workshop ASAP.

**Comment by ickycoolboy** [comment]
I wanted to let you know, the workshop version seems to be "locked" I can't comment or view it or anything.

**Comment by ickycoolboy** [comment]
if you got a previous message saying the workshop version was locked ignore it. for about a week it was locked.

**Comment by Domii894** [comment]
Yeah, I informed patcher about that (realized it some hours ago)
There was an issue with steam. Steam forced him to accept the new workshop-conditions. So it was locked because he didn't do it.
But now all is fine again.
