### ISSUE TITLE
Issue With ADV DUPE 2

### ISSUE THREAD

**Issue by ickycoolboy** [Patcher56/PatchProtect#106]
Users can't interact with their duped contraptions. Mainly they can't physgun them.

**Comment by Domii894** [comment]
Hey, sry but I'm quite busy right now.
I just tested the adv-dupe2 on my server and had no problems with it..
I downloaded the adv-dupe2 directly on github from the wiremod team: https://github.com/wiremod/advdupe2

Maybe you have a buggy/old verison on your server. But it should work at least with this version.
