### ISSUE TITLE
Compatibility with UCLIP mod for ulx?

### ISSUE THREAD

**Issue by ickycoolboy** [Patcher56/PatchProtect#108]
Uclip is a mod for ulx that prevents players from nocliping through the map and other players props. With this addon the prop part works and they can noclip through there own props just fine. However, for entities they can not noclip through there own. Is it possible to fix this?

**Comment by Domii894** [comment]
Actually I cannot say if this is an error by pprotect or not.
But in general, the code doesn't split up between props and entities. So they are handled both at the same way. I just tested, if everything works fine on entities and it does. Maybe the code of uclip doesn't handle entities correctly or even doesn't care about it.
I looked at the code from uclip too and everything should work. But I can't say, if this code gets activated if you try to "clip" through an entitiy.

Can you check please, if you get an error message at the right bottom corner, if you try to noclip through other peoples props?
Does this also happen, if you try to go through entities, which are not owned by yourself?

**Comment by ickycoolboy** [comment]
No Error messages occur and I also can't go through other people's entities.

**Comment by Domii894** [comment]
So you also don't get an patchprotect-information when you try to go through that entity?

**Comment by ickycoolboy** [comment]
If you are talking about prop ownership, it does tell me who the owner is.

**Comment by Domii894** [comment]
No I mean that kind of message:
If you try to pick up a prop from someone else and you're not allowed to do that, then you get a message at the right bottom of the screen. Normally you should also see that, when you try to go through an entity, on which you are not allowed to.
So if that message doesn't come up and you can't pass through the entity, there must something wrong with the ownership-check of uclip. But as I said, I am not sure and don't want to critisize the code from the ulx team, when I have no prooves for that.

**Comment by ickycoolboy** [comment]
It doesn't really seem to be an issue anymore so ill close this.

**Comment by Domii894** [comment]
Strange, but good to hear that!
