### ISSUE TITLE
Cleanup Lua Error

### ISSUE THREAD

**Issue by Dundiddy** [Patcher56/PatchProtect#113]
Just downloaded and i'm getting this funky lua error 

[ERROR] lua/patchprotect/server/cleanup.lua:13: attempt to index local 'o' (a number value)
  1. unknown - lua/patchprotect/server/cleanup.lua:13
   2. foreach - [C]:-1
    3. unknown - lua/patchprotect/server/cleanup.lua:9
     4. unknown - lua/includes/modules/concommand.lua:54

**Comment by Domii894** [comment]
Hi,
I think I know why this error occured. I will fix this later.

Thanks for the bug report.
At least, can you tell me when this error exactly occured? Right aftrr server join or what?

**Comment by Dundiddy** [comment]
I believe it occurs when I click on the cleanup tab, can't say exactly sorry

**Comment by Dundiddy** [comment]
Sorry i'm fairly new to all this how exactly do I edit my file with your new line of code?

**Comment by Dundiddy** [comment]
Nevermind what I said previously I goofed and the addon file name had capitals when I extracted the files

So i'm still getting the same error:

[ERROR] addons/patchprotect/lua/patchprotect/server/cleanup.lua:13: attempt to index local 'o' (a number value)
  1. unknown - addons/patchprotect/lua/patchprotect/server/cleanup.lua:13
   2. foreach - [C]:-1
    3. unknown - addons/patchprotect/lua/patchprotect/server/cleanup.lua:9
     4. unknown - lua/includes/modules/concommand.lua:54

And whats actually happening is when I click on the cleanup tab nothing is coming up and the errors begin

**Comment by Domii894** [comment]
it should be fixed, maybe you use the workshop-version, which is not updated?

**Comment by Dundiddy** [comment]
I downloaded the zip from here

**Comment by Domii894** [comment]
Ok, I'm sorry. I didn't read the error-message carefully enough. This will fix the issue. If it is still occuring, please give me a shout.
Thanks

**Comment by Dundiddy** [comment]
Sorry I didn't reply sooner, but its fixed thanks a heap!
