### ISSUE TITLE
Player Fall Damage Error

### ISSUE THREAD

**Issue by Dundiddy** [Patcher56/PatchProtect#114]
This error is shown whenever a player takes fall damage (I believe)

[ERROR] addons/patchprotect2/lua/patchprotect/server/propprotection.lua:298: attempt to index local 'ply' (a number value)
  1. v - addons/patchprotect2/lua/patchprotect/server/propprotection.lua:298
   2. unknown - lua/includes/modules/hook.lua:84

**Comment by Domii894** [comment]
Hi, why the hell are you getting constantly number values as entities and players. There must be another addon, which produces this error. Nobody else mentioned this kind of error before.

**Comment by Dundiddy** [comment]
It just kinda fixed itself not just a few minutes ago so I'll assume you used some black magic of some kind but thanks!
