### ISSUE TITLE
Fix ur reset command

### ISSUE THREAD

**Issue by Velkon** [Patcher56/PatchProtect#116]
no permission check

**Comment by Domii894** [comment]
Hey Velkon,

sry that I have to say that, but this is a quite bad error-report.
I don't really get out of your (quite short) error-report, WHICH or WHAT "reset-command" you mean.

**Comment by storm37000** [comment]
the command is clientside only, no need for permissions to it.

**Comment by Domii894** [comment]
Thanks for the note.
