### ISSUE TITLE
prop pertection

### ISSUE THREAD

**Issue by BatmanHobo** [Patcher56/PatchProtect#130]
hey so prop protection it doesnt work  I can still kill people with prop and yes I do have it enabled in the q menu.

**Comment by storm37000** [comment]
this addon doesn't have anti prop push so your mistaken on what you think its for.  Prop protection means preventing others from grabbing your stuff and messing with it.

**Comment by Domii894** [comment]
As @storm37000 mentioned, this feature is out of scope of PatchProtect.
