### ISSUE TITLE
Anything spawned before the client enters the game says no owner

### ISSUE THREAD

**Issue by storm37000** [Patcher56/PatchProtect#134]
Anything spawned before the client enters the game says no owner.  Only things that spawn after the player joined the server show their proper owners.  This is a real issue for administration as any staff that are called on to deal with issues wont see who owns the stuff.

**Comment by storm37000** [comment]
It seems to eventually fill out the owner, this may be a bug with the nwvar system which would make it an issue with the base game.

**Comment by Domii894** [comment]
Seems to require detailed investigation.
Unfortunately due to time constraints we are forced to delay reviews of bigger changes.

**Comment by storm37000** [comment]
this can be closed, im pretty sure i fixed this by redoing the way the owner is networked as nwvars are slow to update but net messages can be instant.
