### ISSUE TITLE
[REQUEST/SECURITY] Add superadmin checks to net messages

### ISSUE THREAD

**Issue by storm37000** [Patcher56/PatchProtect#139]
This is a major security flaw that would allow the attacker to modify the blacklists in any way they want to.

**Comment by Domii894** [comment]
Hi,
thank you very much for your contribution.
Unfortunately due to time constraints we are forced to delay reviews of bigger changes.

Since you moved quite some amount of code it takes more time to pick specific changes.
I added the permission checks as proposed by your referenced commit. Thanks.
