### ISSUE TITLE
Anti-Spam is not working

### ISSUE THREAD

**Issue by ryanhemmet** [Patcher56/PatchProtect#84]
I installed the addon to my server. I set the antispam up and set it to not ignore admins. I had a moderator test the antispam and he is able to spam as many as prop as he would like. There were no errors when starting the server so I do not know why this is not working. I have saved the settings after editting the settings as well.

**Comment by Domii894** [comment]
I will close this to clear the issues-section a bit. Feel free to reopen it if you have more information, like when it happens and how I can reproduce it.
As always I can't reproduce your advanced duplicator issues.
Also the issue, that "ignore Admins" doesn't work is fixed (just tested it again for sure)

:)
