### ISSUE TITLE
patchprotect/client/hud.lua:39: Tried to use a NULL entity!

### ISSUE THREAD

**Issue by Bryantdl7** [Patcher56/PatchProtect#92]
[ERROR] addons/prop protection/lua/patchprotect/client/hud.lua:39: Tried to use a NULL entity!
  1. Nick - [C]:-1
   2. fn - addons/prop protection/lua/patchprotect/client/hud.lua:39
    3. unknown - addons/ulib/lua/ulib/shared/hook.lua:105

**Comment by Domii894** [comment]
same as https://github.com/Patcher56/PatchProtect/issues/95
