### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Tigster** [Patcher56/PatchProtect#96]
Error in hook HUDPaint: addons/patchprotect-master/lua/autorun/cppi.lua:49: Tried to use a NULL entity!
stack traceback:
	[C]: in function 'UniqueID'
	addons/patchprotect-master/lua/autorun/cppi.lua:49: in function 'CPPIGetOwner'
	addons/patchprotect-master/lua/patchprotect/client/hud.lua:24: in function 'v'
	lua/includes/modules/hook.lua:84: in function <lua/includes/modules/hook.lua:67>
	[C]: in function '‭‬‌⁬﻿‎⁯⁮⁭'

[ERROR] 
  1. unknown - [C]:-1

**Comment by Domii894** [comment]
Hey Tigster,
thank you for the error report :) I've fixed it already.
If you experience any other issues, just give me a shout and I will have a look on it.
