### ISSUE TITLE
A couple of errors I need to report.

### ISSUE THREAD

**Issue by ickycoolboy** [Patcher56/PatchProtect#97]
1. 
[ERROR] addons/patchprotect/lua/autorun/cppi.lua:49: Tried to use a NULL entity!
  1. UniqueID - [C]:-1
   2. CPPIGetOwner - addons/patchprotect/lua/autorun/cppi.lua:49
    3. unknown - addons/patchprotect/lua/patchprotect/server/cleanup.lua:12
     4. foreach - [C]:-1
      5. unknown - addons/patchprotect/lua/patchprotect/server/cleanup.lua:9
       6. unknown - lua/includes/modules/concommand.lua:54

This one occurs whenever you try to cleanup the map using the patchprotect cleanup menu, the map still cleans up though.

2.
[ERROR] addons/patchprotect/lua/autorun/cppi.lua:49: Tried to use a NULL entity!
  1. UniqueID - [C]:-1
   2. CPPIGetOwner - addons/patchprotect/lua/autorun/cppi.lua:49
    3. CheckPPAdmin - addons/patchprotect/lua/patchprotect/server/propprotection.lua:8
     4. fn - addons/patchprotect/lua/patchprotect/server/propprotection.lua:163
      5. unknown - addons/ulib/lua/ulib/shared/hook.lua:105

3.
[ERROR] addons/patchprotect/lua/autorun/cppi.lua:49: Tried to use a NULL entity!
  1. UniqueID - [C]:-1
   2. CPPIGetOwner - addons/patchprotect/lua/autorun/cppi.lua:49
    3. CheckPPAdmin - addons/patchprotect/lua/patchprotect/server/propprotection.lua:8
     4. CPPICanPhysgun - addons/patchprotect/lua/patchprotect/server/propprotection.lua:91
      5. updateOwnership - addons/uclip/lua/autorun/sv_uclip.lua:35
       6. checkOwnership - addons/uclip/lua/autorun/sh_uclip.lua:46
        7. checkVel - addons/uclip/lua/autorun/sh_uclip.lua:173
         8. fn - addons/uclip/lua/autorun/sh_uclip.lua:205
          9. unknown - addons/ulib/lua/ulib/shared/hook.lua:105

All of these started happening after the gmod update.

P.S: what happened to patchprotect on the workshop?

**Comment by Domii894** [comment]
Hmm, strange... https://github.com/Patcher56/PatchProtect/commit/84932e6d856aca65f97babb0e78d5cee04357a19
6 hours ago I committed this fix to fix that. When did you experience this issues? Just now or some time sooner? Or maybe you didn't update patchprotect?

The workshop version is at the moment exactly the same as the github version, so you can switch over to it. Normally the workshop version is more stable than the github one, because we develop here and workshop only gets the fully developed versions.

**Comment by Domii894** [comment]
This error should be fixed now. I will close this when it is 100%ly fixed :)

**Comment by Domii894** [comment]
Please reopen this issue, if you still experience any of your mentioned bugs. Thanks
