### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by Tigster** [Patcher56/PatchProtect#98]
[ERROR] addons/patchprotect-master/lua/patchprotect/server/buddy.lua:7: attempt to call method 'SteamID' (a nil value)
  1. IsBuddy - addons/patchprotect-master/lua/patchprotect/server/buddy.lua:7
   2. v - addons/patchprotect-master/lua/patchprotect/server/propprotection.lua:312
    3. unknown - lua/includes/modules/hook.lua:84

**Comment by Domii894** [comment]
Thank you for that error report :)
The new system is not that well tested than the old one. It was necessary because of the new gmod update.
This should be fixed in a few seconds :)

**Comment by Tigster** [comment]
That's aight mate
