### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by Tigster** [Patcher56/PatchProtect#99]
[ERROR] addons/patchprotect-master/lua/autorun/cppi.lua:49: Tried to use a NULL entity!
  1. UniqueID - [C]:-1
   2. CPPIGetOwner - addons/patchprotect-master/lua/autorun/cppi.lua:49
    3. CheckPPAdmin - addons/patchprotect-master/lua/patchprotect/server/propprotection.lua:8
     4. v - addons/patchprotect-master/lua/patchprotect/server/propprotection.lua:294
      5. unknown - lua/includes/modules/hook.lua:84
       6. FireBullets - [C]:-1
        7. FireBullet - addons/cw2/lua/weapons/cw_base/sh_bullets.lua:39
         8. unknown - addons/cw2/lua/weapons/cw_base/shared.lua:1263

**Comment by Domii894** [comment]
I interpret this as fixed :P
